#ifndef IFACE_DISCOVERY_H
#define IFACE_DISCOVERY_H
// GENERATED by iface-gen (C++) from schema_Discovery.json — DO NOT EDIT
// package version 0.0.6-api.3 — functional twin of npm @rootintf/iface-discovery
#include "cpp-iface-gen.git/Iface.h"   // the cpp-iface runtime (Iface.h), referenced where it lives
#include <nlohmann/json.hpp>
#include "cpp-json-msg.git/json_msg+ack.h"   // base classes: ::JSON::JSON_Msg / JSON_MsgEffect

namespace reflector_iface { namespace Discovery {  // protocol "Discovery"

inline constexpr const char* PKG_VERSION = "0.0.6-api.3";  // == npm package version
inline const char* const SCHEMA = R"IFACE(
{
  "$id": "https://root-interface.se/protocols/Discovery",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "schemas": {
    "https://root-interface.se/protocols/Discovery/definitions": {
      "$id": "https://root-interface.se/protocols/Discovery/definitions",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "definitions": {
        "_v": {
          "const": "3"
        }
      }
    },
    "https://root-interface.se/protocols/Discovery/MsgDiscover": {
      "$id": "https://root-interface.se/protocols/Discovery/MsgDiscover",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "type": "object",
      "required": [
        "discover",
        "Discovery"
      ],
      "properties": {
        "discover": {
          "type": "object",
          "required": [
            "ttl_msec"
          ],
          "properties": {
            "ttl_msec": {
              "type": "integer"
            }
          }
        },
        "Discovery": {
          "$ref": "definitions#/definitions/_v"
        }
      },
      "x-base": "JSON_Msg"
    },
    "https://root-interface.se/protocols/Discovery/MsgAnnounce": {
      "$id": "https://root-interface.se/protocols/Discovery/MsgAnnounce",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "type": "object",
      "required": [
        "announce",
        "Discovery"
      ],
      "properties": {
        "announce": {
          "type": "object"
        },
        "Discovery": {
          "$ref": "definitions#/definitions/_v"
        }
      },
      "x-base": "JSON_MsgEffect"
    }
  }
}

)IFACE";
inline constexpr const char* VERSION = "3";  // on-wire protocol version (_v)

inline const ::iface_gen::Iface& _iface() { static const ::iface_gen::Iface _i(SCHEMA); return _i; }

// base: JSON_MsgEffect
class JSON_MsgAnnounce : public ::JSON::JSON_MsgEffect {
public:
	JSON_MsgAnnounce(const ::JSON::JSON_MsgEffect& v) : ::JSON::JSON_MsgEffect(v) {}
	static bool validate(const ::JSON::JSON_MsgEffect& v) { return _iface().validate("https://root-interface.se/protocols/Discovery/MsgAnnounce", v); }
	static JSON_MsgAnnounce create_with_cause_merge(const nlohmann::json& cause, const nlohmann::json& body) { return JSON_MsgAnnounce(::JSON::JSON_MsgEffect::create_with_cause_merge(cause, { {"announce", body}, {"Discovery", VERSION} })); }
	static JSON_MsgAnnounce create_with_cause_merge(const nlohmann::json& cause, const std::string& body) { return create_with_cause_merge(cause, nlohmann::json::parse(body)); }
	static JSON_MsgAnnounce create_with_cause_merge(const nlohmann::json& cause, const char* body) { return create_with_cause_merge(cause, nlohmann::json::parse(body)); }
};
// base: JSON_Msg
class JSON_MsgDiscover : public ::JSON::JSON_Msg {
public:
	JSON_MsgDiscover(const ::JSON::JSON_Msg& v) : ::JSON::JSON_Msg(v) {}
	static bool validate(const ::JSON::JSON_Msg& v) { return _iface().validate("https://root-interface.se/protocols/Discovery/MsgDiscover", v); }
	static JSON_MsgDiscover merge(const nlohmann::json& body) { return JSON_MsgDiscover(::JSON::JSON_Msg::merge({ {"discover", body}, {"Discovery", VERSION} })); }
	static JSON_MsgDiscover merge(const std::string& body) { return merge(nlohmann::json::parse(body)); }
	static JSON_MsgDiscover merge(const char* body) { return merge(nlohmann::json::parse(body)); }
};

}} // namespace reflector_iface::Discovery
#endif // IFACE_DISCOVERY_H
