#ifndef IFACE_MESSAGINGENV_H
#define IFACE_MESSAGINGENV_H
// GENERATED by iface-gen (C++) from schema_MessagingEnv.json — DO NOT EDIT
// package version 0.0.6-api.2 — functional twin of npm @rootintf/iface-messagingenv
#include "cpp-iface-gen.git/Iface.h"   // the cpp-iface runtime (Iface.h), referenced where it lives
#include <nlohmann/json.hpp>
#include "cpp-json-msg.git/json_msg+ack.h"   // base classes: ::JSON::JSON_Msg / JSON_MsgEffect

namespace reflector_iface { namespace MessagingEnv {  // protocol "MessagingEnv"

inline constexpr const char* PKG_VERSION = "0.0.6-api.2";  // == npm package version
inline const char* const SCHEMA = R"IFACE(
{
  "$id": "https://root-interface.se/protocols/MessagingEnv",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "schemas": {
    "https://root-interface.se/protocols/MessagingEnv/definitions": {
      "$id": "https://root-interface.se/protocols/MessagingEnv/definitions",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "definitions": {
        "_v": {
          "const": "2"
        }
      }
    },
    "https://root-interface.se/protocols/MessagingEnv/MsgCtrl": {
      "$id": "https://root-interface.se/protocols/MessagingEnv/MsgCtrl",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "type": "object",
      "required": [
        "ctrl-msg",
        "MessagingEnv"
      ],
      "properties": {
        "ctrl-msg": {
          "type": "object",
          "required": [
            "participants",
            "ttl_msec"
          ],
          "properties": {
            "participants": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "address",
                  "protocol",
                  "identification"
                ],
                "properties": {
                  "address": {
                    "type": "string"
                  },
                  "protocol": {
                    "type": "string"
                  },
                  "identification": {
                    "type": "object",
                    "required": [
                      "id"
                    ],
                    "properties": {
                      "id": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            },
            "ttl_msec": {
              "type": "integer"
            },
            "filter": {
              "type": "object",
              "required": [
                "sha256"
              ],
              "properties": {
                "sha256": {
                  "type": "string"
                },
                "spec": {}
              }
            }
          }
        },
        "MessagingEnv": {
          "$ref": "definitions#/definitions/_v"
        }
      },
      "x-base": "JSON_Msg"
    },
    "https://root-interface.se/protocols/MessagingEnv/MsgFilter": {
      "$id": "https://root-interface.se/protocols/MessagingEnv/MsgFilter",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "type": "object",
      "required": [
        "ctrl-filter",
        "MessagingEnv"
      ],
      "properties": {
        "ctrl-filter": {
          "type": "object",
          "required": [
            "sha256",
            "wasm_b64"
          ],
          "properties": {
            "sha256": {
              "type": "string"
            },
            "wasm_b64": {
              "type": "string"
            }
          }
        },
        "MessagingEnv": {
          "$ref": "definitions#/definitions/_v"
        }
      },
      "x-base": "JSON_Msg"
    }
  }
}

)IFACE";
inline constexpr const char* VERSION = "2";  // on-wire protocol version (_v)

inline const ::iface_gen::Iface& _iface() { static const ::iface_gen::Iface _i(SCHEMA); return _i; }

// base: JSON_Msg
class JSON_MsgCtrl : public ::JSON::JSON_Msg {
public:
	JSON_MsgCtrl(const ::JSON::JSON_Msg& v) : ::JSON::JSON_Msg(v) {}
	static bool validate(const ::JSON::JSON_Msg& v) { return _iface().validate("https://root-interface.se/protocols/MessagingEnv/MsgCtrl", v); }
	static JSON_MsgCtrl merge(const nlohmann::json& body) { return JSON_MsgCtrl(::JSON::JSON_Msg::merge({ {"ctrl-msg", body}, {"MessagingEnv", VERSION} })); }
	static JSON_MsgCtrl merge(const std::string& body) { return merge(nlohmann::json::parse(body)); }
	static JSON_MsgCtrl merge(const char* body) { return merge(nlohmann::json::parse(body)); }
};
// base: JSON_Msg
class JSON_MsgFilter : public ::JSON::JSON_Msg {
public:
	JSON_MsgFilter(const ::JSON::JSON_Msg& v) : ::JSON::JSON_Msg(v) {}
	static bool validate(const ::JSON::JSON_Msg& v) { return _iface().validate("https://root-interface.se/protocols/MessagingEnv/MsgFilter", v); }
	static JSON_MsgFilter merge(const nlohmann::json& body) { return JSON_MsgFilter(::JSON::JSON_Msg::merge({ {"ctrl-filter", body}, {"MessagingEnv", VERSION} })); }
	static JSON_MsgFilter merge(const std::string& body) { return merge(nlohmann::json::parse(body)); }
	static JSON_MsgFilter merge(const char* body) { return merge(nlohmann::json::parse(body)); }
};

}} // namespace reflector_iface::MessagingEnv
#endif // IFACE_MESSAGINGENV_H
